### ISSUE TITLE
Add a menu border as part of the theme

### ISSUE THREAD

**Issue by vnmabus** [ppizarror/pygame-menu#390] opened 2022-02-19 00:29 UTC
**Is your feature request related to a problem? Please describe.**
I am trying to define a menu with a border, as in this example:

![bildo](https://user-images.githubusercontent.com/2364173/154777406-f8c54bb5-6364-4f5b-b4b9-577eea41b714.png)

The borders are defined in this file:

![dialog-borders01](https://user-images.githubusercontent.com/2364173/154777465-f04469e9-21f5-4d8b-9eaf-944265383f23.png)

**Describe the solution you'd like**
I would want to be able to define a border for the menu, so that pygame-menu is able to tile it (as opposed to stretching it) and place the corners appropriately. Ideally this option could be made part of a theme.

**Describe alternatives you've considered**
I tried defining that as a background image, but then I would need to define it with the right final dimensions or it would be stretched. I also tried using `menu.get_scrollarea().get_decorator().add_callable`, achieving the image above. The problem with this solution is that I cannot define that in a theme, forcing me to modify each menu separatedly or to create a subclass of `Menu` that applies this by default.

**Comment by ppizarror** [comment] 2022-02-20 00:49
I'll add menu_border_width and menu_border_color. I think these two properties are sufficient

**Comment by vnmabus** [comment] 2022-02-20 01:10
Would it allow using an image to define the border?

**Comment by ppizarror** [comment] 2022-02-20 14:36
Do you have any code to place the image? If I detect the menu_border_color is "baseimage" instance I can execute such function inside the border. The "color" code is much easier, as I can use "rect.inflate" to fill a border

**Comment by vnmabus** [comment] 2022-02-20 14:44
Yes. We are dealing with this problem because we wanted to rewrite [Tuxemon](https://github.com/Tuxemon/Tuxemon)'s UI to use pygame-menu, instead of our own existing UI, but keeping the same look and feel.

I was doing a small test to see feasibility and difficulty of such a change. For that I reused the existing drawing code using `menu.get_scrollarea().get_decorator().add_callable` as I mentioned before. The actual code that draws the image and the borders is this one:

https://github.com/Tuxemon/Tuxemon/blob/bf96fbbf926df5e2f5b5c42e47037e57527db0f8/tuxemon/ui/draw.py#L85

**Comment by vnmabus** [comment] 2022-03-13 17:47
Is there something I can do to advance this issue?

**Comment by ppizarror** [comment] 2022-03-14 00:45
Hi, sorry for the inactivity; I've been short in my free time. I used your code and create new theme params ``border_color`` and  ``border_width``. 

To test it, check new https://github.com/ppizarror/pygame-menu/pull/393, and use the following code:

```
theme = pygame_menu.themes.THEME_DEFAULT.copy()
theme.border_width = 10 # In px

# If you want a menu with border color
theme.border_color = 'red'
menu = MenuUtils.generic_menu(theme=theme, width=250, height=250)
menu.mainloop(surface)

# Test with image
theme.border_color = pygame_menu.BaseImage(pygame_menu.baseimage.IMAGE_EXAMPLE_TILED_BORDER)
menu = MenuUtils.generic_menu(theme=theme, width=250, height=250)
menu.mainloop(surface)
```

Let me know if this solves your issue 😄

**Comment by ppizarror** [comment] 2022-03-19 23:49
> Is there something I can do to advance this issue?

Hi, have you been able to test the new feature? Greetings"!

**Comment by vnmabus** [comment] 2022-03-20 01:07
The border color seems to work, although I couldn't make the image example work... It shows a menu without border to me.

**Comment by ppizarror** [comment] 2022-03-20 01:23
> The border color seems to work, although I couldn't make the image example work... It shows a menu without border to me.

You my friend have spotted an issue! I've already patched, now the code should work perfectly. For instance, you can use any BaseImage method, like scale, and it should work as intended:

```python
theme = pygame_menu.themes.THEME_DEFAULT.copy()
theme.title_font_size = 15
theme.border_color = pygame_menu.BaseImage(pygame_menu.baseimage.IMAGE_EXAMPLE_TILED_BORDER)
theme.border_color.scale2x()
menu = pygame_menu.Menu('Menu with border image', 250, 250, theme=theme)
menu.mainloop(surface)
```

![image](https://user-images.githubusercontent.com/12925256/159144034-9aa2f01c-906f-44b8-a7a9-6504cfa8c6ba.png)

```python
theme = pygame_menu.themes.THEME_DEFAULT.copy()
theme.title_font_size = 15
theme.border_color = pygame_menu.BaseImage(pygame_menu.baseimage.IMAGE_EXAMPLE_TILED_BORDER)
theme.border_color.scale(5, 5)
menu = pygame_menu.Menu('Menu with border image', 250, 250, theme=theme)
menu.mainloop(surface)
```

![image](https://user-images.githubusercontent.com/12925256/159144061-40a78862-9fe9-41a7-a568-af012431656c.png)

**Comment by ppizarror** [comment] 2022-03-20 15:09
Greetings! @vnmabus, I will close this issue and publish it to PyPI. Feel free to create any problem to report bugs or new features.

**Comment by vnmabus** [comment] 2022-03-20 15:11
Yeah, I didn't found any other bug for now. Thank you so much!

**Closed** 2022-03-20 15:11 UTC
Labels: enhancement

**Comment by ppizarror** [comment] 2022-03-20 17:13
Uploaded! https://pypi.org/project/pygame-menu/4.2.6/

**Comment by vnmabus** [comment] 2022-03-27 17:44
A related thing that would be useful is a way to query the size of the menu including the border, for placement purposes. Should I open a new issue for this?

**Comment by ppizarror** [comment] 2022-03-27 18:10
> A related thing that would be useful is a way to query the size of the menu including the border, for placement purposes. Should I open a new issue for this?

That's a nice addition. Let's make a new issue
