### ISSUE TITLE
Joystick down arrow goes up and vice versa

### ISSUE THREAD

**Issue by VnaMaster** [ppizarror/pygame-menu#78] opened 2019-12-10 20:42 UTC
with joystick enabled when i scroll between widgets for some reason up and down joystick arrow are switched. Up goes down and vice versa.. why?

**Comment by ppizarror** [comment] 2019-12-10 20:48
Hi. It's a old issue but I've not time to fix this. Maybe in a couple of hours I'll push some other updates.
See #77

**Comment by VnaMaster** [comment] 2019-12-10 21:02
> 
> 
> Hi. It's a old issue but I've not time to fix this. Maybe in a couple of hours I'll push some other updates.
> See #77



> 
> 
> Hi. It's a old issue but I've not time to fix this. Maybe in a couple of hours I'll push some other updates.
> See #77

Hi, your new updates will include this fix? 
thanks

**Comment by ppizarror** [comment] 2019-12-10 21:40
Yes, all widget handling using joystick will be fixed (I hope)

**Comment by VnaMaster** [comment] 2019-12-11 07:38
ok, i keep watching on releases. Good work with this project by the way.
Amedeo Aquino
*Software Engineer*


Il giorno mar 10 dic 2019 alle ore 22:40 Pablo Pizarro R. <
notifications@github.com> ha scritto:

**Comment by VnaMaster** [comment] 2019-12-12 09:49
Hi Pablo,
any new about fix?
thanks
Amedeo Aquino
*Software Engineer*


Il giorno mer 11 dic 2019 alle ore 08:38 Amedeo Aquino <
amedeo.aquino@gmail.com> ha scritto:

**Comment by ppizarror** [comment] 2019-12-12 14:13
Hi! Can you test the pull request #77, if there's an error let me know.
The main problem is that I cannot test the controls because I don't have any joystick.

**Comment by VnaMaster** [comment] 2019-12-12 14:18
When i come back home tonight i'll test it
Amedeo Aquino
*Software Engineer*


Il giorno gio 12 dic 2019 alle ore 15:13 Pablo Pizarro R. <
notifications@github.com> ha scritto:

**Comment by VnaMaster** [comment] 2019-12-12 18:04
Hi Pablo, tested branch fix-joy-widgets and doesn't work
Amedeo Aquino
*Software Engineer*


Il giorno gio 12 dic 2019 alle ore 15:18 Amedeo Aquino <
amedeo.aquino@gmail.com> ha scritto:

**Comment by VnaMaster** [comment] 2019-12-12 18:08
the behaviour is:
up and down arrow are switched but analog works well
Amedeo Aquino
*Software Engineer*


Il giorno gio 12 dic 2019 alle ore 19:04 Amedeo Aquino <
amedeo.aquino@gmail.com> ha scritto:

**Comment by ppizarror** [comment] 2019-12-13 13:15
I switched up and down arrow keys on pull request. Does it work now?
Thanks for your help 😄

**Comment by VnaMaster** [comment] 2019-12-13 18:32
yes, it works now :) well done.
Can you please merge this branche into master so i can install pygame-menu
module from raspberry pi?
thanks
Amedeo Aquino
*Software Engineer*


Il giorno ven 13 dic 2019 alle ore 14:15 Pablo Pizarro R. <
notifications@github.com> ha scritto:

**Comment by ppizarror** [comment] 2019-12-13 18:53
Can you confirm that the widgets works as intended using joypad, mostly the selector (changing left/right options, applying the option)

**Comment by VnaMaster** [comment] 2019-12-13 19:04
yes
Amedeo Aquino
*Software Engineer*


Il giorno ven 13 dic 2019 alle ore 19:53 Pablo Pizarro R. <
notifications@github.com> ha scritto:

**Comment by ppizarror** [comment] 2019-12-13 21:29
Nice. I'll push the new release now

**Comment by ppizarror** [comment] 2019-12-13 21:47
Closed.

**Closed by ppizarror** 2019-12-13 21:47 UTC
