### ISSUE TITLE
Scrollbar in general not working with touchscreen

### ISSUE THREAD

**Issue by yagui** [ppizarror/pygame-menu#347] opened 2021-05-24 16:02 UTC
**Environment information**
Describe your environment information, such as:
- SO: linux/Raspberry OS
- python version: v3.7
- pygame version: v2.0.1
- pygame-menu version: v4.0.7-master

**Describe the bug**
Scroll bar doesn't respond to touch on the screen. I can't drag the slider from the scroll bar. At some point I try to touch lower in the scroll bar to see if at least I can go down not dragging but jumping to the lower section (I don't know if this make sense), but it also doesn't work. Same test in the computer with the mouse works perfectly. When I try to slide the scroll bar, it seems to gets selected because it changes color, but nothing happen.

**To Reproduce**
I copied the scroll_menu example and added `touchscreen=True` in all menus. The result is I can select buttons, go inside other menu and go back with the X, but scroll bar doesn't respond to touchs.
![video2](https://user-images.githubusercontent.com/4296015/119374557-b482a600-bc87-11eb-8275-6fc41ed868cd.gif)

**Comment by yagui** [comment] 2021-05-24 16:14
I can try to log all pygame events if that helps you to track the bug, or if you want send me a script to test and I'll run it. Thank you

**Comment by ppizarror** [comment] 2021-05-24 17:59
It's strange because I cannot reproduce that using an touch emulator. Can you print the events list read by Scrollbar.update, that is, printing the list within

https://github.com/ppizarror/pygame-menu/blob/master/pygame_menu/widgets/widget/scrollbar.py#L520-L526

That would give me an idea about what events are being processed by the menu

**Comment by ppizarror** [comment] 2021-05-24 17:59
@anxuae hi! Do you experience touchscreen issues regarding scrolling?

**Comment by yagui** [comment] 2021-05-24 18:46
Using the scroll_menu.py example, adding `Touchscreen = True` to all menus and changing windows size to (800,480).

![video3](https://user-images.githubusercontent.com/4296015/119393141-91172580-bc9e-11eb-9969-3943e2086c4a.gif)
[log.txt](https://github.com/ppizarror/pygame-menu/files/6534394/log.txt)

**Comment by yagui** [comment] 2021-05-24 18:57
I'm seeing that there are no check for FINGERUP/DOWN/MOTION in that method. Could that be the problem?
Also, I didn't added in this example, but in my application I use `mouse_enabled=False` and I see most of these conditions are going to evaluate `False`

**Comment by ppizarror** [comment] 2021-05-24 21:06
Yes, you're right. Even the scrollbars do not consider the same configurations as the menu. I do not know how've missed that https://github.com/ppizarror/pygame-menu/blob/0e2814c59fcd45e84c1b335ccd737ee8bb39e427/pygame_menu/_scrollarea.py#L257
I'll push a PR asap

**Comment by ppizarror** [comment] 2021-05-24 21:41
Hi, #349 fixes this issue. However, the solution is far from perfect as the amount of scrolled "dx, dy" is not consistent across different scroll surfaces. I had to figure out the correct maths

**Comment by ppizarror** [comment] 2021-05-24 21:46
I think I've found a better solution, and it was considering the dx, dy are within range (-1, 1), thus, 2*window_size must be applied. Let me know if the PR's solves the issue

**Comment by yagui** [comment] 2021-05-25 14:06
It's working great now for the scroll_menu example, but the scroll in the dropselect or multiselect is still not working (I merged both pull request to test it).

**Comment by ppizarror** [comment] 2021-05-25 16:40
Hi! I've found what was bad in PR. The Frame's ScrollArea object (which includes the ScrollBar widgets) was not properly configured (both menu - for scrolling, and controls settings). Also, the frame did not configure the menu reference for the scrollarea while calling ``make_scrollarea`` method.

I've committed to #349. Let me know about anything! 😎

**Comment by yagui** [comment] 2021-05-25 20:26
Working smoothly now! Thanks!!

**Comment by ppizarror** [comment] 2021-05-25 21:35
Excellent, I'll push the new version on the weekend. Please open any other issue if I'd encounter any issue =)

**Closed by ppizarror** 2021-05-25 21:35 UTC
Labels: bug
